### ISSUE TITLE
Project doesn't not compile

### ISSUE THREAD

**Issue by misterpear** [TagCommander/TagCommander-In-Swift#1]
Hello the team TagCommander !
The project doesn't not compile anymore... I've got this :
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TagCommander", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_TCDebug", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation) 
```
Can you update the project demo please ? 😄

**Comment by TagCommander** [comment]
The demo was created with the "iPhone" versions of the library and you're trying to compile it for the simulators.
Either compile for iPhone or replace the frameworks with the "universal" ones from http://github.com/TagCommander/pods

**Comment by misterpear** [comment]
Okay thanks !
